USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE ECOM_ANALYTICS;
USE SCHEMA OPS;

CREATE SCHEMA IF NOT EXISTS ECOM_ANALYTICS.OPS;

-- Root task must be suspended first before any other graph changes (Snowflake error 091421).
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_START SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_STAGING SUSPEND;

ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_DAILY_KPI SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_GEO_KPI SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_CUSTOMER_REPEAT_METRICS SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_MART SUSPEND;

ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_GEOLOCATION SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_SELLERS SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_REVIEWS SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_PRODUCTS SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_CUSTOMERS SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_PAYMENTS SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_ORDER_ITEMS SUSPEND;
ALTER TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_ORDERS SUSPEND;

DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_DAILY_KPI;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_GEO_KPI;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_CUSTOMER_REPEAT_METRICS;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_MART;

DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_GEOLOCATION;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_SELLERS;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_REVIEWS;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_PRODUCTS;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_CUSTOMERS;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_PAYMENTS;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_ORDER_ITEMS;
DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_STG_ORDERS;

DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_START;

DROP TASK IF EXISTS ECOM_ANALYTICS.OPS.TASK_REFRESH_STAGING;
CREATE OR REPLACE STREAM ECOM_ANALYTICS.OPS.RAW_ORDERS_STREAM
  ON TABLE ECOM_ANALYTICS.RAW.RAW_ORDERS
  APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_START
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
  SELECT CURRENT_TIMESTAMP() AS run_ts;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_ORDERS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_ORDERS AS
SELECT
  order_id,
  customer_id,
  order_status,
  TRY_TO_TIMESTAMP_NTZ(order_purchase_timestamp) AS order_purchase_ts,
  TRY_TO_TIMESTAMP_NTZ(order_approved_at) AS order_approved_ts,
  TRY_TO_TIMESTAMP_NTZ(order_delivered_carrier_date) AS order_delivered_carrier_ts,
  TRY_TO_TIMESTAMP_NTZ(order_delivered_customer_date) AS order_delivered_customer_ts,
  TRY_TO_TIMESTAMP_NTZ(order_estimated_delivery_date) AS order_estimated_delivery_ts
FROM ECOM_ANALYTICS.RAW.RAW_ORDERS;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_ORDER_ITEMS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_ORDER_ITEMS AS
SELECT
  order_id,
  TRY_TO_NUMBER(order_item_id) AS order_item_id,
  product_id,
  seller_id,
  TRY_TO_TIMESTAMP_NTZ(shipping_limit_date) AS shipping_limit_ts,
  TRY_TO_DECIMAL(price, 18, 2) AS price,
  TRY_TO_DECIMAL(freight_value, 18, 2) AS freight_value
FROM ECOM_ANALYTICS.RAW.RAW_ORDER_ITEMS;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_PAYMENTS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_PAYMENTS AS
SELECT
  order_id,
  TRY_TO_NUMBER(payment_sequential) AS payment_sequential,
  payment_type,
  TRY_TO_NUMBER(payment_installments) AS payment_installments,
  TRY_TO_DECIMAL(payment_value, 18, 2) AS payment_value
FROM ECOM_ANALYTICS.RAW.RAW_PAYMENTS;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_CUSTOMERS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_CUSTOMERS AS
SELECT
  customer_id,
  customer_unique_id,
  customer_zip_code_prefix,
  customer_city,
  customer_state
FROM ECOM_ANALYTICS.RAW.RAW_CUSTOMERS;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_PRODUCTS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_PRODUCTS AS
SELECT
  product_id,
  product_category_name,
  TRY_TO_NUMBER(product_weight_g) AS product_weight_g,
  TRY_TO_NUMBER(product_length_cm) AS product_length_cm,
  TRY_TO_NUMBER(product_height_cm) AS product_height_cm,
  TRY_TO_NUMBER(product_width_cm) AS product_width_cm
FROM ECOM_ANALYTICS.RAW.RAW_PRODUCTS;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_REVIEWS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_REVIEWS AS
SELECT
  review_id,
  order_id,
  TRY_TO_NUMBER(review_score) AS review_score,
  review_comment_title,
  review_comment_message,
  TRY_TO_DATE(review_creation_date) AS review_creation_date,
  TRY_TO_TIMESTAMP_NTZ(review_answer_timestamp) AS review_answer_ts
FROM ECOM_ANALYTICS.RAW.RAW_REVIEWS;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_SELLERS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_SELLERS AS
SELECT
  seller_id,
  seller_zip_code_prefix,
  seller_city,
  seller_state
FROM ECOM_ANALYTICS.RAW.RAW_SELLERS;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_STG_GEOLOCATION
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_START
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.STAGING.STG_GEOLOCATION AS
SELECT
  geolocation_zip_code_prefix,
  TRY_TO_DOUBLE(geolocation_lat) AS geolocation_lat,
  TRY_TO_DOUBLE(geolocation_lng) AS geolocation_lng,
  geolocation_city,
  geolocation_state
FROM ECOM_ANALYTICS.RAW.RAW_GEOLOCATION;


CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_REFRESH_MART
  WAREHOUSE = COMPUTE_WH
  AFTER
    ECOM_ANALYTICS.OPS.TASK_STG_ORDERS,
    ECOM_ANALYTICS.OPS.TASK_STG_ORDER_ITEMS,
    ECOM_ANALYTICS.OPS.TASK_STG_PAYMENTS,
    ECOM_ANALYTICS.OPS.TASK_STG_CUSTOMERS,
    ECOM_ANALYTICS.OPS.TASK_STG_PRODUCTS,
    ECOM_ANALYTICS.OPS.TASK_STG_REVIEWS,
    ECOM_ANALYTICS.OPS.TASK_STG_SELLERS,
    ECOM_ANALYTICS.OPS.TASK_STG_GEOLOCATION
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.MART.FCT_ORDERS AS
WITH item_totals AS (
  SELECT order_id, SUM(price) AS items_total, SUM(freight_value) AS freight_total
  FROM ECOM_ANALYTICS.STAGING.STG_ORDER_ITEMS
  GROUP BY order_id
),
payment_totals AS (
  SELECT order_id, SUM(payment_value) AS payment_total
  FROM ECOM_ANALYTICS.STAGING.STG_PAYMENTS
  GROUP BY order_id
),
review_scores AS (
  SELECT order_id, AVG(review_score) AS avg_review_score
  FROM ECOM_ANALYTICS.STAGING.STG_REVIEWS
  GROUP BY order_id
),
geo_dedup AS (
  SELECT
    geolocation_zip_code_prefix,
    AVG(geolocation_lat) AS geolocation_lat,
    AVG(geolocation_lng) AS geolocation_lng
  FROM ECOM_ANALYTICS.STAGING.STG_GEOLOCATION
  GROUP BY geolocation_zip_code_prefix
)
SELECT
  o.order_id,
  o.customer_id,
  c.customer_unique_id,
  c.customer_city,
  c.customer_state,
  gd.geolocation_lat AS customer_lat,
  gd.geolocation_lng AS customer_lng,
  o.order_status,
  o.order_purchase_ts,
  o.order_delivered_customer_ts,
  o.order_estimated_delivery_ts,
  it.items_total,
  it.freight_total,
  pt.payment_total,
  rs.avg_review_score,
  CASE
    WHEN o.order_delivered_customer_ts IS NULL OR o.order_estimated_delivery_ts IS NULL THEN NULL
    WHEN o.order_delivered_customer_ts > o.order_estimated_delivery_ts THEN 1
    ELSE 0
  END AS is_delayed,
  DATE_TRUNC('day', o.order_purchase_ts) AS order_date
FROM ECOM_ANALYTICS.STAGING.STG_ORDERS o
LEFT JOIN ECOM_ANALYTICS.STAGING.STG_CUSTOMERS c
  ON o.customer_id = c.customer_id
LEFT JOIN geo_dedup gd
  ON c.customer_zip_code_prefix = gd.geolocation_zip_code_prefix
LEFT JOIN item_totals it
  ON o.order_id = it.order_id
LEFT JOIN payment_totals pt
  ON o.order_id = pt.order_id
LEFT JOIN review_scores rs
  ON o.order_id = rs.order_id;


CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_REFRESH_DAILY_KPI
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_REFRESH_MART
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.MART.DAILY_KPI AS
SELECT
  order_date AS kpi_date,
  COUNT(DISTINCT order_id) AS total_orders,
  COALESCE(SUM(payment_total), 0) AS gmv,
  CASE
    WHEN COUNT(DISTINCT order_id) = 0 THEN 0
    ELSE COALESCE(SUM(payment_total), 0) / COUNT(DISTINCT order_id)
  END AS aov,
  AVG(avg_review_score) AS avg_review_score,
  AVG(is_delayed::FLOAT) * 100 AS delayed_order_pct
FROM ECOM_ANALYTICS.MART.FCT_ORDERS
WHERE order_date IS NOT NULL
GROUP BY order_date;

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_REFRESH_GEO_KPI
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_REFRESH_MART
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.MART.GEO_KPI AS
SELECT
  customer_state,
  customer_city,
  ROUND(customer_lat, 4) AS customer_lat,
  ROUND(customer_lng, 4) AS customer_lng,
  COUNT(DISTINCT order_id) AS total_orders,
  SUM(payment_total) AS gmv,
  AVG(is_delayed::FLOAT) * 100 AS delayed_order_pct
FROM ECOM_ANALYTICS.MART.FCT_ORDERS
WHERE customer_lat IS NOT NULL
  AND customer_lng IS NOT NULL
GROUP BY
  customer_state,
  customer_city,
  ROUND(customer_lat, 4),
  ROUND(customer_lng, 4);

CREATE OR REPLACE TASK ECOM_ANALYTICS.OPS.TASK_REFRESH_CUSTOMER_REPEAT_METRICS
  WAREHOUSE = COMPUTE_WH
  AFTER ECOM_ANALYTICS.OPS.TASK_REFRESH_MART
AS
CREATE OR REPLACE TABLE ECOM_ANALYTICS.MART.CUSTOMER_REPEAT_METRICS AS
WITH cust_orders AS (
  SELECT
    customer_unique_id,
    COUNT(DISTINCT order_id) AS order_count
  FROM ECOM_ANALYTICS.MART.FCT_ORDERS
  WHERE customer_unique_id IS NOT NULL
  GROUP BY customer_unique_id
)
SELECT
  COUNT(*) AS total_customers,
  COUNT_IF(order_count > 1) AS repeat_customers,
  CASE
    WHEN COUNT(*) = 0 THEN 0
    ELSE COUNT_IF(order_count > 1) * 100.0 / COUNT(*)
  END AS repeat_customer_pct
FROM cust_orders;

-- RESUME / EXECUTE handled by pipeline/trigger_snowflake_tasks.py (root task must resume last).